export const SET_LOADING = "SET_LOADING";
export const REMOVE_LOADING = "REMOVE_LOADING";
export const GET_GENRES = "GET_GENRES";

export const FETCH_MOVIES_DISCOVER = "FETCH_MOVIES_DISCOVER";
export const FETCH_MOVIES_POPULAR = "FETCH_MOVIES_POPULAR";
