export const SET_LOADING = "SET_LOADING";
export const REMOVE_LOADING = "REMOVE_LOADING";
export const GET_GENRES = "GET_GENRES";
export const GET_CONFIG = "GET_CONFIG";
export const SET_SELECTED = "SET_SELECTED";

export const FETCH_MOVIES_GENRES = "FETCH_MOVIES_GENRES";
export const FETCH_MOVIES_DISCOVER = "FETCH_MOVIES_DISCOVER";
export const FETCH_MOVIES_POPULAR = "FETCH_MOVIES_POPULAR";
export const SET_MOVIES_LOADING = "SET_MOVIES_LOADING";
export const REMOVE_MOVIES_LOADING = "REMOVE_MOVIES_LOADING";

export const CHANGE_PAGE = "CHANGE_PAGE";
