export const SET_LOADING = "SET_LOADING";
export const REMOVE_LOADING = "REMOVE_LOADING";
export const GET_GENRES = "GET_GENRES";
export const GET_CONFIG = "GET_CONFIG";
export const SET_SELECTED = "SET_SELECTED";
export const SET_SORTBY = "SET_SORTBY";
export const SET_SEARCH = "SET_SEARCH";

export const FETCH_MOVIES_GENRES = "FETCH_MOVIES_GENRES";
export const FETCH_MOVIES_DISCOVER = "FETCH_MOVIES_DISCOVER";
export const FETCH_MOVIES_POPULAR = "FETCH_MOVIES_POPULAR";
export const FETCH_MOVIES_SEARCH = "FETCH_MOVIES_SEARCH";
export const FETCH_MOVIE_DETAILS = "FETCH_MOVIE_DETAILS";
export const FETCH_MOVIE_RECOMMENDATION = "FETCH_MOVIE_RECOMMENDATION";

export const SET_MOVIES_LOADING = "SET_MOVIES_LOADING";
export const REMOVE_MOVIES_LOADING = "REMOVE_MOVIES_LOADING";
export const CHANGE_PAGE = "CHANGE_PAGE";
